### ISSUE TITLE
I have shifted the main parts into PyTorch.

### ISSUE THREAD

**Issue by erow** [koukyo1994/pytorch-disentanglement-lib#1]
I just find someone has the same idea. 
Maybe you need this, https://github.com/erow/disentanglement_lib.

**Comment by koukyo1994** [comment]
Thanks for the info, but what I quite don't like about disentanglement_lib is `gin-config` things. That's the reason I started this project but soon after I started, I found someone with the same spirit have already done this - https://github.com/nmichlo/disent - so I stopped working on this.

**Comment by erow** [comment]
I agree. `gin-config` makes this library behave like a program. Because I am a researcher in this area, the least modification may be a better solution for further study.
